version: "3.9"

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"      # Spark master port
      - "8080:8080"      # Spark master web UI
    volumes:
      - ./output:/opt/output
      - ./app:/app 
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_DIR=/tmp/spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"      # Spark worker 1 web UI
    volumes:
      - ./output:/opt/output
      - ./app:/app 
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_DIR=/tmp/spark-worker
    depends_on:
      - spark-master
    ports:
      - "8082:8081"      # Worker UI exposed at different host port
    volumes:
      - ./app:/app 
      - ./output:/opt/output 
    networks:
      - spark-network

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_DIR=/tmp/spark-worker
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - ./output:/opt/output
      - ./app:/app 
    networks:
      - spark-network

  spark-history-server:
    image: bitnami/spark:latest
    container_name: spark-history
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
    ports:
      - "18080:18080"    # History server UI
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:

volumes:
  spark-events: